dict = {'www.kiplinger.com': 7, 'www.savingforcollege.com': 4, 'www.tax.ny.gov': 7, 'drive.google.com': 37,
        'www.lifecycleinvesting.net': 2, 'papers.ssrn.com': 72, 'www.aacalc.com': 2, 'www.wpwealth.com': 3,
        'mba.tuck.dartmouth.edu': 2, 'www.efficientfrontier.com': 16, 'www.amazon.com': 219, 'medium.com': 7,
        'www.ifa.com': 4, 'www.wallstreetphysician.com': 1, 'portfoliocharts.com': 37, 'yalealumnimagazine.com': 1,
        'www.npr.org': 31, 'www.irs.gov': 37, 'investor.vanguard.com': 44, 'www.morningstar.com': 98,
        'thecollegeinvestor.com': 1, 'obliviousinvestor.com': 1, 'www.reddit.com': 46, 'www.bestbuy.com': 2,
        'www.whitecoatinvestor.com': 25, 'www.youtube.com': 697, 'gisanddata.maps.arcgis.com': 19,
        'www.seattletimes.com': 49, 'www.worldometers.info': 45, 'www.nytimes.com': 170, 'www.google.com': 75,
        'www.nbcnews.com': 6, 'abcnews.go.com': 9, 'www.who.int': 5, 'twitter.com': 147, 'www.cnbc.com': 202,
        'www.cdc.gov': 43, 'amp.cnn.com': 6, 'www.theatlantic.com': 15, 'finance.yahoo.com': 111,
        'www.bloomberg.com': 135, 'www.taiwannews.com.tw': 5, 'www.biorxiv.org': 3, 'api.nationalgeographic.com': 2,
        'www.axios.com': 8, 'www.telegraph.co.uk': 2, 'www.wsj.com': 60, 'fee.org': 2, 'www.statista.com': 1,
        'www.ad.nl': 1, 'www.doctorofcredit.com': 5, 'www.chase.com': 11, 'am.jpmorgan.com': 4, 'www.bbc.co.uk': 7,
        'personal.vanguard.com': 35, 'patch.com': 1, 'www.sacbee.com': 1, 'accounts.chase.com': 3,
        'www.proper.insure': 5, 'www.mysmartmove.com': 1, 'www.statefarm.com': 1, 'factsanddetails.com': 1,
        'en.wikipedia.org': 280, 'www.realclearpolitics.com': 4, 'www.dallasfed.org': 13, 'i.pinimg.com': 3,
        'covid19tracker.health.ny.gov': 1, 'www.healthdata.org': 4, 'www.marketwatch.com': 190,
        'www.barrons.com': 22, 'www.theguardian.com': 46, 'blogs.imf.org': 1, 'www.washingtonpost.com': 43,
        'www.ft.com': 21, 'www.cebm.net': 1, 'www.thestreet.com': 20, 'www.federalreserve.gov': 25,
        'www.cfr.org': 1, 'www.nationsreportcard.gov': 1, 'mediabiasfactcheck.com': 2,
        'www.businessinsider.com': 32, 'www.project-syndicate.org': 1, 'www.igmchicago.org': 1, 'www.cato.org': 1,
        'www.usnews.com': 8, 'www.edweek.org': 1, 'www.forbes.com': 29, 'gizmodo.com': 4, 'www.nber.org': 3,
        'financialpost.com': 1, 'www.vwlawyers.ca': 1, 'www.canadianlawyermag.com': 1, 'www.pallettvalo.com': 1,
        'www.ncbi.nlm.nih.gov': 5, 'www.propublica.org': 6, 'www.urban.org': 2, 'www.aarp.org': 7, 'www.bls.gov': 9,
        'flic.kr': 74, 'www.flickr.com': 37, 'www.fox5vegas.com': 1, 'www.usatoday.com': 11, 'www.ncsl.org': 1,
        'www.nolo.com': 3, 'www.brookings.edu': 3, 'petetheplanner.com': 1, 'www.bizjournals.com': 3,
        'www.themuse.com': 2, 'www.huffpost.com': 2, 'www.the-wau.com': 2, 'www.foxbusiness.com': 6,
        'www.thebalancecareers.com': 2, 'www.fedweek.com': 2, 'www.glassdoor.com': 3, 'studentloanhero.com': 5,
        'www.insidehighered.com': 1, 'www.vox.com': 2, 'www.ssa.gov': 13, 'www.arcgis.com': 2, 'www.etf.com': 34,
        'www.tsp.gov': 2, 'www.streetinsider.com': 1, 'www.retaildive.com': 1, 'www.investopedia.com': 83,
        'www.cbsnews.com': 11, 'www.investing.com': 27, 'www.cbssports.com': 1, 'rogermontgomery.com': 1,
        'www.thebalance.com': 1, 'covid19.healthdata.org': 1, 'techstartups.com': 3, 'covidtracking.com': 1,
        'www.borsaitaliana.it': 3, 'docs.google.com': 45, 'www.ccn.com': 15, 'tradingeconomics.com': 13,
        'youtu.be': 221, 'www.multpl.com': 45, 'fortune.com': 4, 'www.ig.com': 16, 'www.ecb.europa.eu': 6,
        'www.tweedy.com': 1, 'nypost.com': 22, 'www.cnn.com': 31, 'www.dailymail.co.uk': 15, 'm.youtube.com': 27,
        'www.vice.com': 2, 'earlyretirementnow.com': 14, 'www.reuters.com': 40, 'www.reviewjournal.com': 9,
        'www.euroweeklynews.com': 1, 'investornews.vanguard': 8, 'mobile.twitter.com': 6, 'larrysummers.com': 3,
        'marginalrevolution.com': 1, 'www.nbcchicago.com': 1, 'www.fidelity.com': 18, 'seekingalpha.com': 84,
        'camelcamelcamel.com': 2, 'www.medrxiv.org': 1, 'www.bbc.com': 15, 'lasvegassun.com': 1,
        'www.theverge.com': 5, 'lnns.co': 5, 'www.latimes.com': 5, 'slate.com': 3, 'www.sciencenews.org': 1,
        'web.archive.org': 11, 'www.flightradar24.com': 1, 'variety.com': 3, 'www.schwab.com': 15,
        'coronavirus.jhu.edu': 1, 'www.politico.com': 2, 'awealthofcommonsense.com': 42, 'www.nea.org': 2,
        'content.time.com': 4, 'news.efinancialcareers.com': 1, 'www.weforum.org': 4, 'thehill.com': 7,
        'thereformedbroker.com': 4, 'cmmid.github.io': 1, 'institutefordiseasemodeling.github.io': 1,
        'www.livescience.com': 10, 'www.frontiersin.org': 4, 'www.nbcwashington.com': 1, 'www.dailywire.com': 1,
        'www.worldatlas.com': 3, 'www.linkedin.com': 2, 'hbr.org': 2, 'www.rgj.com': 1, 'www.nasdaq.com': 8,
        'www.econ.yale.edu': 3, 'www.msn.com': 4, 'www.defenseone.com': 1, 'www.jstor.org': 1, 'web.mit.edu': 1,
        'ofdollarsanddata.com': 8, 'www.caixinglobal.com': 2, 'www.foxnews.com': 1, 'brooklyneagle.com': 1,
        'dnyuz.com': 4, 'www-stat.wharton.upenn.edu': 1, 'www.aha.org': 2, 'www.inquirer.com': 5,
        'www.post-gazette.com': 1, 'blogs.microsoft.com': 3, 'www.google.co.uk': 1, 'www.phillyvoice.com': 2,
        'regiehammblog.wordpress.com': 1, 'us.dimensional.com': 8, 'money.cnn.com': 21, 'www.thedailybeast.com': 1,
        'march.aps.org': 7, 'www.independent.co.uk': 3, 'www.nejm.org': 1, 'ca.investing.com': 2,
        'www.autonews.com': 1, 'www.zagline.com': 1, 'en.people.cn': 4, 'www.kingcounty.gov': 1,
        'www.facebook.com': 3, 'publichealthinsider.com': 1, 'www.doh.wa.gov': 1, 'www.cidrap.umn.edu': 3,
        'www.rev.com': 2, 'nilepost.co.ug': 3, 'www.gatesnotes.com': 1, 'fillingupthecorners.wordpress.com': 1,
        'www.scmp.com': 16, 'komonews.com': 1, 'www.sciencemag.org': 5, 'bigcharts.marketwatch.com': 2,
        'www.popsci.com': 1, 'cdn.vox-cdn.com': 1, 'www.imperial.ac.uk': 1, 'www.prnewswire.com': 7,
        'www.channelnewsasia.com': 2, 'api.wsj.net': 3, 'www.japantimes.co.jp': 1, 'www.jpost.com': 5,
        'archive.vn': 10, 'www.statnews.com': 3, 'www.standard.co.uk': 1, 'www.thesun.co.uk': 1,
        'www.straitstimes.com': 2, 'www.mlanet.org': 4, 'www.ssrn.com': 1, 'theconversation.com': 1,
        'www.niid.go.jp': 3, 'journals.plos.org': 1, 'vanguardblog.com': 2, 'www.artofmanliness.com': 3,
        'sigmanutrition.com': 1, 'www.culturalhealthsolutions.com': 2, 'chrismasterjohnphd.com': 1, 'tim.blog': 3,
        'daveasprey.com': 1, 'www.mercola.com': 1, 'liveindex.org': 1, 'www.zerohedge.com': 42,
        'en.m.wikipedia.org': 8, 'www.epochtimes.com': 2, 'assets.publishing.service.gov.uk': 1,
        'www.law.cornell.edu': 3, 'www.interactivebrokers.com': 18, 'ibkr.info': 3, 'www.gov.uk': 2,
        'lpfurniturecomponents.com': 2, 'valenciatheaterseating.com': 2, 'www.ebay.com': 4, 'relaxtheback.com': 1,
        'www.samsclub.com': 2, 'tahoe.ca.gov': 4, 'store.hp.com': 1, 'www.assetprotectionplanners.com': 1,
        'home.treasury.gov': 7, 'www.moneychimp.com': 4, 'quotes.morningstar.com': 50, 'money.com': 3,
        'www.starcapital.de': 1, 'advisors.vanguard.com': 9, 'fundresearch.fidelity.com': 1,
        'thefinancebuff.com': 6, 'www.mydogtag.com': 5, 'www.cuisinart.com': 1, 'smile.amazon.com': 23,
        'www.flyertalk.com': 1, 'cyclehealthinfo.com': 3, 'www.ellipticalreviews.com': 3,
        'techcommunity.microsoft.com': 1, 'www.microsoft.com': 1, 'www.costco.com': 3, 'www.vizio.com': 1,
        'www.macobserver.com': 2, 'slickdeals.net': 13, 'www.rtings.com': 5, 'www.cordcuttersnews.com': 1,
        'www.howtogeek.com': 2, 'www.early-retirement.org': 6, 'www.cnet.com': 2, 'www.avsforum.com': 1,
        'www.klipsch.com': 1, 'www.walmart.com': 3, 'topdogtips.com': 1, 'shop.furryfreshness.com': 1,
        'www.whole-dog-journal.com': 1, 'www.happyhound.com': 1, 'etactics.com': 7, 'nces.ed.gov': 1,
        'jalopnik.com': 1, 'www.volvocars.com': 1, 'fourpillarfreedom.com': 4, 'www.1500days.com': 1,
        'www.collaborativefund.com': 2, 'www.jdpower.com': 3, 'www.caranddriver.com': 3, 'forum.leasehackr.com': 2,
        'www.ogaracoach.com': 1, 'www.aoamerch.com': 1, 'www.autoblog.com': 1, 'www.ag.idaho.gov': 2,
        'dogsthat.com': 1, 'www.millennial-revolution.com': 1, 'forum.mrmoneymustache.com': 9,
        'www.mymoneyblog.com': 2, 'www.withings.com': 1, 'www.dcrainmaker.com': 1, 'elder-law.com': 2,
        'q1medicare.com': 2, 'www.exteriores.gob.es': 6, 'www.golden-visa-portugal.info': 1,
        'www.blevinsfranks.com': 2, 'iversonssnowshoes.com': 1, 'www.outdoorgearlab.com': 2,
        'www.switchbacktravel.com': 1, 'www.fabersnowshoes.com': 1, 'www.concretenetwork.com': 1,
        'www.Awardblinds.com': 1, 'www.rottentomatoes.com': 21, 'www.imdb.com': 188, 'www.newyorker.com': 51,
        'topdocumentaryfilms.com': 1, 'www.thechinahustlefilm.com': 1, 'theleveragedindexer.com': 4,
        'www.cmegroup.com': 28, 'www.advisorperspectives.com': 16, 'fred.stlouisfed.org': 36,
        'www.mrmoneymustache.com': 1, 'rootofgood.com': 1, 'www.firethefamily.com': 1,
        'www.financialsamurai.com': 1, 'marriagekidsandmoney.com': 1, 'thefioneers.com': 1, 'www.proshares.com': 33,
        'prnt.sc': 16, 'www.portfoliovisualizer.com': 1068, 'www.fedprimerate.com': 7, 'web.stanford.edu': 11,
        'www.wisdomtree.com': 10, 'wantelbos.github.io': 23, 'gofile.io': 17, 'www.filehosting.org': 6,
        'financial-charts.effingapp.com': 5, 'thefelderreport.com': 3, 'i.imgur.com': 44, 'ibb.co': 32,
        'www.dropbox.com': 9, 'www.sec.gov': 24, 'github.com': 2, 'www.thierry-roncalli.com': 3,
        's000.tinyupload.com': 15, 'investresolve.com': 4, 'www.engadget.com': 1, 'allocatesmartly.com': 3,
        'ufile.io': 7, 'polygon.io': 2, 'www.barchart.com': 13, 'marketdata.websol.barchart.com': 2,
        'stockcharts.com': 11, 'graniteshares.com': 1, 'www.cboe.com': 9, 'ny.hazy.cc': 3, 'pages.stern.nyu.edu': 3,
        'faculty.mccombs.utexas.edu': 2, 'www.ddnum.com': 5, 'www.bridgewater.com': 10, 'www.nyu.edu': 3,
        'direxioninvestments.onlineprospectus.net': 10, 'www.guggenheiminvestments.com': 5,
        'www.visualcapitalist.com': 4, 'www.trendlineprofits.com': 1, 'markets.ft.com': 5, 'www.spglobal.com': 2,
        'www.institutionalinvestor.com': 8, 'riskcenter.berkeley.edu': 2, 'www.q-group.org': 2,
        'www.sas.upenn.edu': 2, 'www.splithistory.com': 6, 'io9.gizmodo.com': 1, 'www.finra.org': 5,
        'wheel.orats.com': 8, 'ycharts.com': 3, 'www.mayoclinic.org': 2, 'emoticoncentral.com': 2,
        'iborrowdesk.com': 13, 'upload.wikimedia.org': 3, 'greatergood.berkeley.edu': 1, 'www.backcountry.com': 1,
        'www.exofficio.com': 2, 'www.chihuly.com': 1, 'browncoffeeco.com': 2, 'www.martindareff.com': 4,
        'fs.blog': 6, 'imgur.com': 68, 'www.columbia.edu': 2, 'www.investresolve.com': 2, 'www.researchgate.net': 3,
        'www.investingdaily.com': 2, 'www.portfolio-performance.info': 1, 'www.artemiscm.com': 1, 'www.soa.org': 2,
        'etfdb.com': 17, 'www.etfscreen.com': 2, 'www.treasury.gov': 11, 'articles': 1, 'www.ishares.com': 17,
        'news.ycombinator.com': 3, 'www.direxion.com': 16, 'performance.morningstar.com': 8, 'www.m1finance.com': 4,
        'sipa.columbia.edu': 1, 'news.google.com': 1, 'www.frbsf.org': 5, 'gbr.pepperdine.edu': 3,
        'www.wolframalpha.com': 5, 'ddnum.com': 4, 'www.etfreplay.com': 1, 'www.macrotrends.net': 6,
        'www.theocc.com': 6, 'sixfigureinvesting.com': 3, 'pastebin.com': 14, 'poseidon01.ssrn.com': 6,
        'www.wisdomtree.eu': 14, 'rparetf.com': 4, 'www.nasdaqtrader.com': 2, 'optimalrebalancing.tk': 2,
        'www.fool.com': 13, 'm.imgur.com': 1, 'www.indexologyblog.com': 1, 'www.tradingview.com': 1,
        'www.ivolatility.com': 4, 'catalyst-insights.com': 12, 'www.pimco.com': 15, 'threadreaderapp.com': 3,
        'threader.app': 1, 'static.seekingalpha.com': 1, 'i.postimg.cc': 2, 'markets.businessinsider.com': 6,
        'jasonzweig.com': 1, 'canadiancouchpotato.com': 1, 'www1.interactivebrokers.com': 2, 'www.deshaw.com': 3,
        'www.economist.com': 9, 'breakingthemarket.com': 2, 'cs.uwaterloo.ca': 1, 'www.eecs.harvard.edu': 1,
        'som.yale.edu': 3, 'accounts.profunds.com': 3, 'www.federalregister.gov': 1, 'www.pnas.org': 1,
        'postimages.org': 22, 'thesawmillgrill.com': 2, 'celebsroll.com': 1, 'www.amundietf.fr': 1,
        'etf.dws.com': 1, 'www.lyxoretf.fi': 1, 'www.ssga.com': 3, 'www.buyupside.com': 1, 'goo.gl': 1,
        'lawreview.vermontlaw.edu': 2, 'www.cambridge.org': 3, 'www.wiwi.uni-muenster.de': 3, 'abload.de': 21,
        'www.schwabfunds.com': 1, 'www.youinvest.co.uk': 4, 'www.globalxetfs.com': 1, 'spintwig.com': 1,
        'teddykoker.com': 11, 'www.hl.co.uk': 3, 'doublelinefunds.com': 3, 'register.gotowebinar.com': 2,
        'www.priceactionlab.com': 4, 'www.bostonfed.org': 1, 'tinyurl.com': 11, 'greentradertax.com': 1,
        'rhsfinancial.com': 2, 'lmgtfy.com': 1, 'textuploader.com': 1, 'blogs.cfainstitute.org': 4,
        'soranews24.com': 1, 'www.math.nyu.edu': 4, 'www.khanacademy.org': 2, 'www.learnfuturestoday.com': 2,
        'www.metopera.org': 1, 'www.netflix.com': 13, 'www.rogerebert.com': 7, 'www.amostbeautifulthing.com': 1,
        'www.dailymotion.com': 5, 'screenanarchy.com': 1, 'www.sfreporter.com': 1, 'm.imdb.com': 2,
        'ntlive.nationaltheatre.org.uk': 4, 'www.hollywoodreporter.com': 3, 'www.screenbinge.com': 1,
        'jerrywbrown.com': 1, 'www.mrflamm.com': 1, 'www.hbo.com': 3, 'screener.fidelity.com': 3,
        'www.merriam-webster.com': 7, 'www.justwatch.com': 1, 'www.nakamichi-usa.com': 1, 'soylent.com': 1,
        'blog.bestamericanpoetry.com': 2, 'www.grc.com': 1, 'www.vangoghmuseum.nl': 1, 'blogs.reuters.com': 1,
        'coastguard.dodlive.mil': 1, 'www.nationalgeographic.com': 1, 'www.jsonline.com': 1, 'www.scribd.com': 1,
        'www.ivacy.com': 4, 'www.fathomevents.com': 1, 'www.seattleweekly.com': 4, 'time.com': 3,
        'embed.ted.com': 2, 'www.iwm.org.uk': 1, 'www.nouse.co.uk': 1, 'wbonds.blogspot.com': 1,
        'letterboxd.com': 1, 'renewcanceltv.com': 10, 'www.pbs.org': 8, 'www.burghisland.com': 1,
        'tickets.thebigsickmovie.com': 2, 'www.therecord.com': 1, 'search.yahoo.com': 1, 'philscamino.com': 1,
        'www.findingbabel.com': 1, 'www.ntnu.edu': 1, 'www.reelhouse.org': 1, 'www.bleeckerstreetmedia.com': 2,
        'mashable.com': 2, 'www.express.co.uk': 1, 'www.regmovies.com': 1, 'www.amctheatres.com': 1,
        'www.cinemark.com': 1, 'www.quora.com': 3, 'mobunited.wordpress.com': 1, 'www.slashfilm.com': 1,
        'www.ntsb.gov': 1, 'www.thrillingdetective.com': 2, 'www.criterion.com': 1, 'www.thestranger.com': 1,
        'trailers.apple.com': 1, 'www.thephantomoftheopera.com': 1, 'events.nationalgeographic.com': 3,
        'moneyfornothingthemovie.org': 1, 'moviepilot.com': 1, 'www.wired.com': 2, 'www.filmmovement.com': 2,
        'www.nleomf.org': 1, 'www.sfgate.com': 1, 'takingnote.blogs.nytimes.com': 1, 'www.jewishideas.org': 1,
        'www.theregister.co.uk': 1, 'www.dna.caltech.edu': 1, 'www.slate.com': 8, 'www.amundietf.lu': 1,
        'www.tesla.com': 1, 'support.microsoft.com': 1, 'www.ftb.ca.gov': 3, 'www.mysolo401k.net': 3,
        'dawhois.com': 1, 'www.worldjerseys.com': 1, 'www.bloombergquint.com': 4, 'thebullelephant.com': 1,
        'www.indeed.com': 5, 'educationdata.org': 2, 'lenderfi.servicingdivision.com': 4,
        'www.mers-servicerid.org': 17, 'ww3.freddiemac.com': 1, 'www.knowyouroptions.com': 2, 'www.opm.gov': 12,
        'www.gao.gov': 1, 'elderaffairs.state.fl.us': 3, 'taxfoundation.org': 1, 'www.acepnow.com': 2,
        'www.fightcancer.org': 2, 'finviz.com': 5, 'www.usglobaletfs.com': 1, 'schrts.co': 14, 'www.bea.gov': 6,
        'www.techtimes.com': 2, 'www.mdpi.com': 1, 'www.bogleheads.org': 46, 'blogs.uoregon.edu': 2,
        'us.econoday.com': 1, 'quotes.yourdictionary.com': 2, 'www.gebele.com': 4, 'vinepair.com': 1,
        'www.dol.gov': 3, 'www.trendsmap.com': 3, 'www.thoughtco.com': 1, 'www.ibtimes.com': 1,
        'www.mauldineconomics.com': 3, 'edition.cnn.com': 1, 'africa.businessinsider.com': 1, 'www.dw.com': 1,
        'asia.nikkei.com': 3, 'memegenerator.net': 1, 'citywireusa.com': 5, 'wealthtrack.com': 7,
        'www.americanbanker.com': 1, 'rationalreminder.ca': 6, 'media1.tenor.com': 1, 'datausa.io': 4,
        'retirementincomejournal.com': 1, 'www.investors.com': 3, 'wallstreetonparade.com': 2,
        'www.plainsallamerican.com': 1, 'www.philadelphiafed.org': 2, 'moneyfortherestofus.com': 3,
        'markets.cboe.com': 5, 'www.gsam.com': 6, 'fairwaywealth.com': 3, 'www.asianews.it': 2,
        'thumbor.forbes.com': 1, 'www.niaaa.nih.gov': 1, 'www.depositaccounts.com': 1, 'www.investivdaily.com': 1,
        'www.economicprincples.org': 1, 'www.philosophicaleconomics.com': 17, 'www.stlouisfed.org': 1,
        'www.ivey.uwo.ca': 1, 'news.3m.com': 8, 'www.futurescopes.com': 2, 'www.kitces.com': 5,
        'www.tdainstitutional.com': 2, 'www.health.gov.au': 1, 'www.oregonlive.com': 1,
        'www.project-risk-manager.com': 1, 'stories.starbucks.com': 1, 'www8.gsb.columbia.edu': 1,
        'www.chcoc.gov': 1, 'm.investing.com': 5, 'pdfs.semanticscholar.org': 1, 'moneychimp.com': 2,
        'www.koyfin.com': 2, 'investors.southwest.com': 2, 'www.coinbase.com': 1, 'www.tradersmagazine.com': 1,
        'www.briefing.com': 1, 'docs.retirementpartner.com': 2, 'www.lostoak.com': 8, 'image.slidesharecdn.com': 1,
        'jlcollinsnh.com': 5, 'www.gutenberg.org': 12, 'qz.com': 2, 'howlongagogo.com': 1, 'www.spiegel.de': 1,
        'humbledollar.com': 7, 'virological.org': 1, 'www.mphonline.org': 1, 'prosperion.us': 7,
        'www.berkshirehathaway.com': 1, 'www.etfrc.com': 3, 'www.crsp.org': 4, 'oakmark.com': 2,
        'paulmerriman.com': 9, 'www.nature.com': 4, 'www.fisherinvestments.com': 1, 'www.newyorkfed.org': 8,
        'www.roycefunds.com': 2, 'www.callan.com': 6, 'cheddar.com': 1, 'cheezburger.com': 2, 'www.ons.gov.uk': 6,
        'news.harvard.edu': 5, 'investmentresearchdynamics.com': 1, 'www.ftportfolios.com': 2, '247wallst.com': 1,
        'dqydj.com': 9, 'www.brainyquote.com': 1, 'pbs.twimg.com': 2, 'www.theoptionsguide.com': 11,
        'www.gambling.com': 1, 'ahdictionary.com': 2, 'www.instituteforsupplymanagement.org': 1,
        'www.dividend.com': 3, 'www.yardeni.com': 7, 'www.naceweb.org': 1, 'www.omaha.com': 3,
        'www.conference-board.org': 1, 'www.calculatedriskblog.com': 8, 'data.bls.gov': 12,
        'www.researchaffiliates.com': 30, 'www.hiyoooo.com': 1, 'www.rawstory.com': 1,
        'en.oxforddictionaries.com': 1, 'wsj.com': 12, 'english.stackexchange.com': 1, 'amp.timeinc.net': 1,
        'www.noradsanta.org': 1, 'graphics.wsj.com': 2, 'www.schroders.com': 1, 'timedotcom.files.wordpress.com': 1,
        'postimg.cc': 7, 'money.usnews.com': 3, 'abc13.com': 1, 'www.britannica.com': 1, 'www.pymnts.com': 1,
        'inflationdata.com': 1, 'www.ftse.com': 1, 'www.spindices.com': 1, 'vignette.wikia.nocookie.net': 3,
        'imarketsignals.com': 1, 'www.mathinvestdecisions.com': 1, 'institutional.vanguard.com': 5,
        'www.bing.com': 4, 'www.americanfunds.com': 1, 'americanfundsretirement.retire.americanfunds.com': 1,
        'tickertape.tdameritrade.com': 2, 'www.lpsm.paris': 1, 'www.isthisthebottom.com': 1, 'appleinsider.com': 1,
        'books.google.com': 2, 'www.housingrisk.org': 1, 'berkshirehathaway.com': 1, 'www.census.gov': 1,
        'theirrelevantinvestor.com': 2, 'www.nyse.com': 3, 'www.sifma.org': 1, 'cdn.history.com': 1,
        'investorplace.com': 1, 'thepatternsite.com': 4, 'samuelssonsrapport.se': 2, 'traderhq.com': 1,
        'finance.google.com': 1, 'm.popkey.co': 1, 'hostimg.co': 1, 'www.sciencedirect.com': 8,
        'www.princeton.edu': 2, 'markets.wsj.com': 2, 'www.jpx.co.jp': 1, 'www.crestmontresearch.com': 5,
        'www.economicpolicyjournal.com': 2, 'mathworld.wolfram.com': 1, 'ritholtz.com': 4, 'hosted.ap.org': 1,
        'www.astrologicalinvesting.com': 1, 'www.theonion.com': 3, 'www.nydailynews.com': 1, 'www.quandl.com': 2,
        'us.spindices.com': 10, 'in.reuters.com': 1, 'quote.morningstar.com': 5, 'media.pimco-global.com': 2,
        'www.xe.com': 6, 'www.vanguard.com': 1, 'vanguard.com': 1, 'ruthkrishnan.com': 1,
        'philosophicaleconomics.wordpress.com': 3, 'www.bearnobull.com': 1, 's113.photobucket.com': 4,
        'mebfaber.com': 4, 'www.immediateannuities.com': 1, 'www.lostsprings.com': 3, 'investorsolutions.com': 1,
        'dilbert.com': 5, 'www.golemxiv.co.uk': 2, 'blogs.wsj.com': 1, 'fairmark.com': 2, 'espn.go.com': 1,
        'publications.credit-suisse.com': 1, 'help.yahoo.com': 2, 'droughtmonitor.unl.edu': 2, 'bigcharts.com': 1,
        'www.valuewalk.com': 4, 'nzbirdsonline.org.nz': 7, 'www.fns.usda.gov': 1, 'i113.photobucket.com': 1,
        'online.wsj.com': 3, 'www.hussman.net': 1, 'politicalcalculations.blogspot.com': 4, 'crawlingroad.com': 2,
        'buzz.money.cnn.com': 1, 'www.nyse.tv': 1, 'www.jumbocdinvestments.com': 1, 'www.crossingwallstreet.com': 2,
        'www.alsosprachanalyst.com': 1, 'hussmanfunds.com': 1, 'primes.utm.edu': 1, 'usatoday30.usatoday.com': 1,
        'video.cnbc.com': 1, 'myloanweb.com': 12, 'app.lenderfi.com': 33, 'www.enterprisenews.com': 1,
        'www.indexuniverse.com': 3, 'socialize.morningstar.com': 5, 'www.tothetick.com': 2, 'www.ritholtz.com': 2,
        'pragcap.com': 2, 'www.mcoscillator.com': 3, 'www.chrismartenson.com': 2, 'www.minyanville.com': 2,
        'thelasvegasinformer.com': 2, 'www.theatlanticwire.com': 1, 'www.lenderfi.com': 12,
        'www.mortgagenewsdaily.com': 48, 'www.amerihome.com': 6, 'bsifinancial.com': 1,
        'www.consumerfinance.gov': 40, 'www.consumeraffairs.com': 7, 'www.housingwire.com': 5,
        'www.madfientist.com': 2, 'gailmarcarelli.com': 1, 'www.gov.ca.gov': 8, 'www.expert1031.com': 1,
        'better.com': 24, 'www.domini.com': 5, 'efficientfrontier.com': 3, 'www.kkwc.com': 2,
        'www.palmspringstaxandtrustlawyers.com': 2, 'www.justetf.com': 7, 'www.de.vanguard': 1,
        'www.morningstar.co.uk': 1, 'support.apple.com': 2, 'www.checkbook.org': 1, 'geha.com': 1,
        'www.fepblue.org': 1, 'www.aetnafeds.com': 1, 'uhcvirtualretiree.com': 1, 'www.afspa.org': 1,
        'www.geha.com': 9, 'www.uhc.com': 2, 'retirementoptimizer.com': 3, 'speedtalkmobile.com': 1,
        'www.libertywireless.com': 2, 'prepaid.t-mobile.com': 1, 'federalnewsnetwork.com': 1,
        'www.liveoakbank.com': 1, 'retirementplans.vanguard.com': 1, 'opensocialsecurity.com': 2,
        'www.benefitspro.com': 1, 'www.kff.org': 5, 'insurance.arkansas.gov': 1, 'ratereview.healthcare.gov': 1,
        'www.cms.gov': 2, 'necsi.edu': 3, 'faculty.chicagobooth.edu': 4, 'funds.aqr.com': 4,
        'grandstreetwm.files.wordpress.com': 3, 'grandstreetwm.wordpress.com': 9, 'www.azasrs.gov': 2,
        'investorjunkie.com': 1, 'rewards.fidelity.com': 5, 'www.jasonhsu.org': 1, 'www.crsp.com': 2,
        'www.anetstation.com': 2, 'vimeo.com': 3, 'americansongwriter.com': 2, 'www.bnymellonretirement.com': 1,
        'www.iiforums.com': 1, 'www.iinews.com': 1, 'www.iflscience.com': 3, 'www.chicagobooth.edu': 1,
        'www.aqr.com': 29, 'www.dodgeandcox.com': 1, 'individual.troweprice.com': 1, 'www.bridgeway.com': 1,
        'www.marecordings.com': 1, 'www.theelectricrecordingco.com': 9, 'emmaswift.bandcamp.com': 3,
        'archive.org': 15, 'www.rollingstone.com': 6, 'theartsdesk.com': 1, 'www.stereophile.com': 1,
        'parttimeaudiophile.com': 1, 'www.analogplanet.com': 1, 'passengermusic.com': 4, 'www.allmusic.com': 2,
        'www.timesofisrael.com': 1, 'nyti.ms': 5, 'gillianwelch.com': 1, 'www.setlist.fm': 3, 'xpn.org': 28,
        'www.wrti.org': 13, 'peterattiamd.com': 3, 'www.kuvo.org': 4, 'faroutmagazine.co.uk': 3,
        'www.metacritic.com': 1, 'www.flavorwire.com': 2, 'open.spotify.com': 1, 'www.cardiffmiller.com': 2,
        'emojipedia.org': 2, 'bobsboots.com': 1, 'www.pavlo.com': 1, 'www.bancsabadell.com': 1,
        'www.bankrate.com': 16, 'themortgagereports.com': 3, 'www.firsttechfed.com': 2,
        'www.mortgagecalculator.biz': 2, 'reali.com': 1, 'www.interactivemortgage.com': 1, 'www.loancabin.com': 9,
        'imgbb.com': 7, 'frugalprofessor.com': 5, 'en.selectra.info': 2, 'usavingsbank.com': 6,
        'www.thetruthaboutmortgage.com': 2, 'www.fhfa.gov': 22, 'singlefamily.fanniemae.com': 30,
        'www.networkcapital.net': 4, 'www.cashcallmortgage.com': 1, 'nahbnow.com': 3, 'interactivemortgage.com': 9,
        'www.dallasnews.com': 3, 'www.lendingtree.com': 2, 'bobdylan.lnk.to': 1, 'www.zillow.com': 16,
        'www2.bancorp.com': 2, 'pfloans.provident.com': 2, 'www.americanexpress.com': 19, 'www.freddiemac.com': 9,
        'guide.freddiemac.com': 7, 'intercontinentalcapital.com': 5, 'www.calculator.net': 8, 'njlta.org': 2,
        'owning.com': 6, 'www.benzinga.com': 1, 'www.mtgprofessor.com': 21, 'www.figure.com': 1, 'www.yelp.com': 4,
        'www.loandepot.com': 3, 'www.vertex42.com': 4, 'apple.news': 4, 'www.findamortgagebroker.com': 1,
        'patitleratingbureau.org': 1, 'www.hsh.com': 2, 'www.loanlimits.org': 1, 'www.mykeystoneloan.com': 1,
        'www.radiantitledirect.com': 2, 'loans.loandepot.com': 2, 'www.bournscu.coop': 9,
        'www.nmlsconsumeraccess.org': 1, 'www.libreoffice.org': 4, 'www.penfed.org': 4,
        'www.elitehomefunding.com': 1, 'www.equifax.com': 1, 'www.AHCLending.com': 2, 'www.federaltitle.com': 5,
        'www.better.com': 2, 'selling-guide.fanniemae.com': 11, 'www.fanniemae.com': 3, 'www.usekeystone.com': 6,
        'mortgage.sibcycline.com': 2, 'Www.Americanexpress.com': 2, 'www.bbb.org': 1, 'www.owning.com': 1,
        'findamortgagebroker.com': 2, 'www.nerdwallet.com': 6, 'www.uwm.com': 1,
        'nationalmortgageprofessional.com': 1, 'www.northpointe.com': 11, 'www.safecu.org': 1,
        'www.calculatestuff.com': 1, 'www.navyfederal.org': 7, 'www2.optimalblue.com': 3, 'img4.imagetitan.com': 1,
        'www.calcxml.com': 1, 'lenkiefer.com': 1, 'www.interest.com': 1, 'online.citi.com': 4,
        'thepoorpeopleofparis.com': 1, 'bluegrasstoday.com': 2, 'kcsm.org': 1, 'www.radiodeluxe.com': 1,
        'beardo1.libsyn.com': 1, 'www.kcrw.com': 1, 'wclv.ideastream.org': 1, 'www.bobsboots.com': 1,
        'www.discogs.com': 1, 'www.internet-radio.com': 2, 'www.ictax.admin.ch': 2, 'forum.mustachianpost.com': 1,
        'www.revenue.ie': 7, 'www2.deloitte.com': 1, 'www.charteredaccountants.ie': 2, 'www.bradford-delong.com': 1,
        'support.varomoney.com': 2, 'faq.hmbradley.com': 1, 'www.hmbradley.com': 2, 'www.hatchbank.com': 1,
        'research2.fdic.gov': 1, 'www.kegerator.com': 1, 'www.roundhillinvestments.com': 1,
        'rnm.simon.rochester.edu': 2, 'community.rationalreminder.ca': 1, 'www.choosefi.com': 2,
        'videos.dimensional.com': 3, 'www.dimensional.com': 4, 'multifactorworld.com': 3,
        'fortunefinancialadvisors.com': 7, 'alphaarchitect.com': 11, 'www.msci.com': 17, 'www.twocenturies.com': 4,
        'boglefunds.com': 1, 'johncbogle.com': 13, 'link.springer.com': 1, 'ssrn.com': 1,
        'research.ftserussell.com': 1, 'valuestockgeek.com': 2, 'www.gmo.com': 6, 'kaiserpartner.bank': 1,
        'podcasts.apple.com': 3, 'www.nhtsa.gov': 1, 'tiremeetsroad.com': 2, 'www.adamsmith.org': 1,
        'www.wellsfargo.com': 6, 'www.privatebank.citibank.com': 2, 'www.wellsfargorelo.com': 1,
        'www.merrilledge.com': 1, 'promo.bankofamerica.com': 1, 'apply.chase.com': 1, 'www.raymondjames.com': 1,
        'www.svb.com': 1, 'chaseprivateclient.chase.com': 2, 'www.valuepenguin.com': 1, 'panampost.com': 1,
        'research.stlouisfed.org': 1, 'www.harborfreight.com': 6, 'www.mpoweruk.com': 2, 'www.weibull.com': 2,
        'batteryuniversity.com': 4, 'shop.advanceautoparts.com': 1, 'www.napaonline.com': 1,
        'www.batteriesplus.com': 1, 'www.aftermarketnews.com': 1, 'www.batteryfaq.org': 1, 'www.indiegogo.com': 1,
        'www.etrade.wallst.com': 8, 'www.avantisinvestors.com': 14, 'www.bespokepremium.com': 1,
        'www.videntfunds.com': 3, 'core-4.com': 1, 'osampodcast.libsyn.com': 3, 'www.osam.com': 6,
        'pillarcapital.com': 1, 'www.prudentllc.com': 1, 'www.logicafunds.com': 11, 't.co': 2,
        'www.theinvestorspodcast.com': 1, 'www.oldschoolvalue.com': 8, 'aswathdamodaran.blogspot.com': 3,
        'www.blackrock.com': 3, 'www.pwlcapital.com': 5, 'famafrench.dimensional.com': 1, 'ivinvestor.com': 1,
        'youtube.com': 1, 'www.invesco.com': 4, 'www.altruistfa.com': 3, 'www.valuesignals.com': 2,
        'www.joshuakennon.com': 3, 'etfsite.alphaarchitect.com': 1, 'www.fortunefinancialadvisors.com': 6,
        'www.fortunefinancialadvisors.c': 4, 'www.robeco.com': 1, 'www.niftyindices.com': 2,
        'www.dictionary.com': 1, 'corporatefinanceinstitute.com': 2, 'www.fa-mag.com': 3, 'www.dinuzzo.com': 2,
        'acquirersmultiple.com': 4, 'falkenblog.blogspot.com': 3, 'www.businessdictionary.com': 1,
        'marketbusinessnews.com': 1, 'www.albertbridgecapital.com': 1, 'mailchi.mp': 2, 'www.acquirersfund.com': 1,
        'www.stitcher.com': 1, 'images.aqr.com': 1, 'www.portfolioeinstein.com': 1, 'www.royceinvest.com': 1,
        'onlinelibrary.wiley.com': 3, 'mutualfunds.com': 2, 'scholar.harvard.edu': 2, 'investorfieldguide.com': 9,
        'bit.ly': 1, 'interactive.researchaffiliates.com': 5, 'lu.spdrs.com': 2, 'www.trackinsight.com': 1,
        'www.valisure.com': 2, 'fedretire.net': 6, 'news.morningstar.com': 2, 'thenextweb.com': 2,
        'www.consumerreports.org': 1, 'arstechnica.com': 5, 'www.yahoo.com': 2, 'www.mdvip.com': 2,
        'www.dmrpublications.com': 1, 'www.ici.org': 3, 'www.ivoletf.com': 3, 'kfafunds.com': 2,
        'www.grantspub.com': 1, 'news.bloomberglaw.com': 1, 'www.convertunits.com': 1, 'www.healthcare.gov': 2,
        'www.bpas.com': 1, 'www.vanguardcharitable.org': 3, 's23.q4cdn.com': 2, 'www.airlinepilotforums.com': 1,
        'www.thevillages.com': 11, 'www.trilogylife.com': 4, 'theacademyvillage.com': 1, 'arizonaexperience.org': 1,
        'www.mysuncoast.com': 7, 'www.lakeandsumterstyle.com': 7, 'www.55places.com': 2, 'groupthink.kinja.com': 3,
        'www.golfat55.com': 2, 'www.vanguard.ch': 2, 'honestppe.supply': 2, 'www.riverbendhealth.shop': 1,
        'www.masQd.com': 1, 'www.tombihn.com': 1, 'shop.atoms.com': 1, 'cambridgemask.com': 6, 'www.lalinen.com': 1,
        'breathesafeair.com': 1, 'coronavirus.health.ok.gov': 1, 'accumed.com': 1, 'seniorcare.com.sg': 4,
        'fixthemask.medium.com': 2, 'halolife.io': 1, 'www.iwillteachyoutoberich.com': 1, 'benefitsattorney.com': 1,
        'www.archerytrade.org': 3, 'www.baenebooks.com': 1, 'www.thefreedictionary.com': 1,
        'www.yourdictionary.com': 1, 'en.wiktionary.org': 3, 'www.poetryfoundation.org': 3,
        'www.scotthyoung.com': 4, 'www.radiolab.org': 1, 'www.nyjournalofbooks.com': 1, 'www.foliosociety.com': 8,
        'www.abebooks.co.uk': 1, 'skin-horse.com': 1, 'interactivebrokers.com': 8, 'www.networkworld.com': 2,
        'www.dividendgrowthinvestor.com': 1, 'ibkb.interactivebrokers.com': 1, 'support.robinhood.com': 1,
        's1.q4cdn.com': 1, 'investors.interactivebrokers.com': 1, 'www.optionseducation.org': 1,
        'www.interactivebrokers.eu': 1, 'forums.hardwarezone.com.sg': 3, 'www.home.saxo': 2,
        'www.businesswire.com': 2, 'ibkr.com': 2, 'mysterysequels.com': 1, 'www.iheart.com': 1,
        'www.overdrive.com': 2, 'www.c-span.org': 4, 'www.tpr.org': 2, 'www.shelterpub.com': 1,
        'boundlessbook.com': 1, 'www.goodreads.com': 12, 'www.pepysdiary.com': 2, 'allthingsliberty.com': 1,
        'www.walterdeemer.com': 1, 'gutenberg.ca': 1, 'www.penguinrandomhouse.com': 1, 'founders.archives.gov': 2,
        'rover.ebay.com': 1, 'chrisleoonline.com': 1, 'www.writermag.com': 1, 'publicdomainreview.org': 1,
        'www.newstatesman.com': 4, 'quoteinvestigator.com': 2, 'www.barnesandnoble.com': 1, 'sites.google.com': 1,
        'www.buzzfeed.com': 2, 'warwick.ac.uk': 1, 'www.hup.harvard.edu': 1, 'www.nybooks.com': 1,
        'www.historicalclimatology.com': 1, 'www.nysoclib.org': 2, 'library.nysoclib.org': 2,
        '99percentinvisible.org': 2, 'inhabitat.com': 1, 'www.edge.org': 1, 'www.travelbooks.co.uk': 1,
        'www.johnsandford.org': 1, 'a.co': 3, 'www.the-american-interest.com': 1, 'lisalutz.com': 1,
        'www.planetebook.com': 2, 'www.davidkeltz.com': 1, 'www.simonandschuster.com': 1,
        'www.thamesandhudson.com': 1, 'www.ted.com': 6, 'www.tmswiki.org': 1, 'www.gladwell.com': 1,
        'live.huffingtonpost.com': 1, 'www.fantasticfiction.co.uk': 7, 'www.bpl.org': 1, 'charlierose.com': 1,
        'www.vanityfair.com': 1, 'www.bulwer-lytton.com': 1, 'shakespeare.mit.edu': 1, 'www.vcpost.com': 1,
        'www.dhspriory.org': 1, 'xkcd.com': 1, 'www.caminodesantiago.me': 1, 'chrome.google.com': 1,
        'fivethirtyeight.com': 2, 'www.jurisjurjevics.com': 1, 'www.amazon.co.uk': 2, 'chronicle.com': 1,
        'www.bakadesuyo.com': 4, 'www.modernlibrary.com': 4, 'www.anthonydoerr.com': 1, 'plato.stanford.edu': 2,
        'www.kc.frb.org': 2, 'www.informationisbeautiful.net': 4, 'www.robertburns.org.uk': 1,
        'www.thebookoflife.org': 4, 'www.jamescamerononline.com': 1, 'www.litigationandtrial.com': 1,
        'bloody-disgusting.com': 1, 'www.locusmag.com': 2, 'www.sf-encyclopedia.com': 2,
        'www.cleavermagazine.com': 1, 'www.snopes.com': 1, 'wmbriggs.com': 1, 'www.ryanholiday.net': 1,
        'thoughtcatalog.com': 3, 'www.tiaa.org': 3, 'community.morningstar.com': 1, 'www.pauldoiron.com': 1,
        'byfat.xxx': 2, 'blog.anguscroll.com': 8, 'www.ioccc.org': 1, 'www.motorbiscuit.com': 2,
        'www.britishmuseum.org': 1, 'www.emilypost.com': 1, 'www.formsofaddress.info': 1,
        'www.inspectorpekkala.com': 1, 'suite.io': 1, 'rickferri.com': 1, 'rogerlowenstein.com': 1,
        'www.scholarshare529.com': 1, 'getpocket.com': 1, 'www.smithsonianmag.com': 1, 'press.uchicago.edu': 1,
        'www.microcenter.com': 3, 'www.newegg.com': 1, 'taylorpearson.me': 3, 'mutinyfund.com': 1,
        'tgwastewater.com': 1, 'www.infiltratorwater.com': 1, 'www.opensignal.com': 1, 'www.straighttalk.com': 1,
        'www.usa.gov': 1, 'bulletins.ncrec.gov': 1, 'www.rinnai.us': 1, 'basc.pnnl.gov': 2, 'www.homedepot.com': 1,
        'www.tacocomfort.com': 2, 'whatsnewonnetflix.com': 1, 'flicksurfer.com': 1, 'instantwatcher.com': 1,
        'www.pastemagazine.com': 1, 'www.newsday.com': 1, 'www.digitaltrends.com': 1, 'netflixtvshowsreview.com': 6,
        'www.instantwatcher.com': 1, 'www.desmoinesregister.com': 1, 'help.netflix.com': 5, 'www.dailydot.com': 1,
        'www.today.com': 3, 'www.newsweek.com': 2, 'wegotthiscovered.com': 1, 'www.space.com': 1, 'www.hulu.com': 1,
        'www.iheartbritishtv.com': 1, 'acronymsandslang.com': 2, 'www.cinemax.com': 3, 'www.vpnranks.com': 5,
        'lostinspacerobot.com': 1, 'wwhan12.wordpress.com': 1, 'tv.avclub.com': 1, 'www.ifc.com': 1,
        'www.purevpn.com': 3}
print(sorted(dict.items(), key=lambda x: x[1], reverse=True))
